const fs = require("fs");

const html = fs.readFileSync("index.html", "utf8");
const css = fs.readFileSync("styles.css", "utf8");
const js = fs.readFileSync("game.js", "utf8");

const checks = [
  ["canvas exists", html.includes('<canvas id="field"')],
  ["throw slider exists", html.includes('id="throwSlider"')],
  ["defense list exists", html.includes('id="defenseList"')],
  ["matchup preview exists", html.includes('id="matchupCard"') && css.includes(".matchup-card") && css.includes(".preview-grid")],
  ["defense edit controls exist", html.includes('id="defenseEditButton"') && html.includes('id="dutyEditButton"') && html.includes('id="saveDefenseButton"') && html.includes('id="resetDefenseButton"')],
  ["add point button exists", html.includes('id="addPointButton"')],
  ["delete point button exists", html.includes('id="deletePointButton"')],
  ["save play button exists", html.includes('id="savePlayButton"')],
  ["route slot controls exist", html.includes('id="saveNameInput"') && html.includes('id="saveSlotButton"') && html.includes('id="deleteSlotButton"') && html.includes('id="slotList"')],
  ["speed controls exist", html.includes('class="speedButton active"') && html.includes('id="pauseButton"')],
  ["replay button exists", html.includes('id="replayButton"') && html.includes("Replay")],
  ["replay scrubber exists", html.includes('id="replayScrubber"') && html.includes('id="frameBackButton"') && html.includes('id="frameForwardButton"')],
  ["replay marker strip exists", html.includes('id="markerStrip"') && html.includes("replay event markers")],
  ["three plays", (js.match(/name: "/g) || []).length >= 6],
  ["defense calls", js.includes("defenseCalls") && js.includes("Edge Blitz")],
  ["defense shape storage", js.includes("defenseStorageKey") && js.includes("loadDefenseOverrides") && js.includes("persistDefenseOverrides")],
  ["defense layout override", js.includes("defenseLayoutForCall") && js.includes("state.defenseOverrides") && js.includes("captureDefenseLayout")],
  ["defense edit dragging", js.includes("state.defenseEdit") && js.includes('kind: "defense"') && js.includes("setDefensePoint")],
  ["defense duty cycling", js.includes("state.dutyEdit") && js.includes("cycleDefenseDuty") && js.includes('"rush", "press", "man", "hook", "curl", "flat", "deep"')],
  ["defense duty persistence", js.includes("trait: p.trait || defenseTrait") && js.includes("normalizeDuty(override.trait)") && js.includes("trait: p.trait || defenseTrait(p.id)")],
  ["zone duty split", js.includes('"hook"') && js.includes('"curl"') && js.includes('"flat"') && js.includes('"deep"')],
  ["zone duty helpers", js.includes("normalizeDuty") && js.includes("isZoneDuty") && js.includes("zoneLandmark")],
  ["zone duty leverage", js.includes('defender.trait === "hook"') && js.includes('defender.trait === "curl"') && js.includes('defender.trait === "flat"') && js.includes('defender.trait === "deep"')],
  ["zone duty movement", js.includes("isZoneDuty(d.trait)") && js.includes("const zone = zoneLandmark(d)")],
  ["defense save controls", js.includes("saveCurrentDefense") && js.includes("resetCurrentDefense") && js.includes("saveDefenseButton.addEventListener")],
  ["defense saved display", js.includes("saved shape") && css.includes("#defenseEditButton[aria-pressed=\"true\"]") && css.includes("#dutyEditButton[aria-pressed=\"true\"]")],
  ["defense snapshot", js.includes("defenseEdit: state.defenseEdit") && js.includes("dutyEdit: state.dutyEdit") && js.includes("savedDefenseCalls: Object.keys") && js.includes("defenseShape: state.defense.map")],
  ["defense duty HUD", js.includes("Duties ${duties}") && js.includes("p.id}:${p.trait}")],
  ["matchup preview logic", js.includes("computeMatchupPreview") && js.includes("previewRoutePoint") && js.includes("defenderLeverage")],
  ["matchup preview rendering", js.includes("renderMatchupPreview") && js.includes("Matchup preview") && js.includes("Hot risk")],
  ["matchup preview updates", js.includes("renderScout();") && js.includes("renderMatchupPreview();") && js.includes("throwSlider.addEventListener")],
  ["matchup preview field lines", js.includes("drawPreviewLines") && js.includes("preview.rows.slice(0, 3)") && js.includes("Field lines show the top three preview reads")],
  ["matchup preview line styling", js.includes("ctx.setLineDash(index === 0 ? [] : [8, 6])") && js.includes("row.grade >= 66") && js.includes("row.grade < 42")],
  ["preview result delta", js.includes("preSnapPreview") && js.includes("previewDeltaText") && js.includes("previewDelta")],
  ["preview delta outcomes", js.includes('outcome === "sack"') && js.includes("closed the window") && js.includes("holding erased the gain")],
  ["preview delta styling", css.includes(".preview-delta") && css.includes("var(--blue)")],
  ["preview delta snapshot", js.includes("preSnapPreview: state.preSnapPreview") && js.includes("previewDelta: state.result")],
  ["throw timing", js.includes("throwSlider") && js.includes("throwTime")],
  ["longer play timing", html.includes('value="2.2"') && js.includes("routeDuration = 3.6") && js.includes("maxPlayTime = 6.2")],
  ["route point editing", js.includes("addPointNear") && js.includes("setRoutePoint")],
  ["route point deletion", js.includes("deletePointNear") && js.includes("state.deletePoint")],
  ["route save storage", js.includes("localStorage") && js.includes("saveCurrentPlay") && js.includes("loadSavedRoutes")],
  ["route save slots", js.includes("normalizeSavedRoutes") && js.includes("savedBookForPlay") && js.includes("activeSavedSlot") && js.includes("selectSavedSlot")],
  ["route slot deletion", js.includes("deleteActiveSlot") && js.includes("deleteSlotButton.addEventListener")],
  ["route slot rendering", js.includes("renderSlotList") && js.includes("routeSlotSummary") && css.includes(".slot-card.active")],
  ["legacy route migration", js.includes("legacyStorageKey") && js.includes('"legacy-1"') && js.includes('"Saved 1"')],
  ["saved route snapshot", js.includes("savedPlayNames") && js.includes("routeOverrides: Object.keys")],
  ["saved slot snapshot", js.includes("savedSlots: savedBookForPlay().slots.map") && js.includes("activeSavedSlot: activeSavedSlot()")],
  ["drive advancement", js.includes("advanceDrive") && js.includes("state.down")],
  ["analysis reads", js.includes("evaluateReceivers") && js.includes("QB評価")],
  ["catch clarity", js.includes("resolveCatch") && js.includes("finishRunAfterCatch") && js.includes("CATCH")],
  ["player orientation", js.includes("angleLerp") && js.includes("backpedalToward") && js.includes("cutFlash")],
  ["read game", js.includes("chooseActualDefense") && js.includes("gradeCall") && js.includes("Coach")],
  ["football contact", js.includes("finishSack") && js.includes("hitPenalty") && js.includes("sackRadius")],
  ["round player markers", js.includes("ctx.arc(0, 0, radius") && !js.includes("roundedRectPath")],
  ["pass protection", js.includes("baseLine") && js.includes("updatePassProtection") && js.includes("pocketWidth")],
  ["screen release", js.includes("screenReleaseTime") && js.includes("screenReleased") && js.includes("SCREEN RELEASE")],
  ["rb pass protection", js.includes("screenProtectPoint") && js.includes('rusher.id === "LB"') && js.includes("blocker.id === \"H\"")],
  ["screen target logic", js.includes("screenBonus") && js.includes("screenReleased() ?")],
  ["screen snapshot", js.includes("screenReleased: screenReleased()") && js.includes("screenReleaseTime: screenReleaseTime()")],
  ["screen wall lead blockers", js.includes("activeScreenCatch") && js.includes("screenWallTarget") && js.includes("ol.screenLead = true")],
  ["screen wall slowdown", js.includes("screenWallSlowdown") && js.includes("defender.screenPicked")],
  ["screen wall snapshot", js.includes("screenWall: state.line.filter") && js.includes("screenPicks: state.defense.filter")],
  ["screen wall replay state", js.includes("screenLead: p.screenLead") && js.includes("screenPicked: p.screenPicked")],
  ["block contact quality", js.includes("blockContactQuality") && js.includes("facingDot") && js.includes("contact.quality")],
  ["block quality replay", js.includes("blockQuality: p.blockQuality") && js.includes("blockQuality: Math.max")],
  ["block quality display", js.includes("Block ${bestBlock.toFixed(2)}") && js.includes("p.blockQuality || 0) * 4")],
  ["block result classification", js.includes("classifyBlockResult") && js.includes('"drive"') && js.includes('"holding"') && js.includes('"shed"')],
  ["block result replay", js.includes("blockResult: p.blockResult") && js.includes("blockResults:")],
  ["holding coach penalty", js.includes("holdingPenalty") && js.includes("Holding-")],
  ["holding penalty enforcement", js.includes("enforceHoldingPenalty") && js.includes("10") && js.includes("HOLDING")],
  ["holding players snapshot", js.includes("holdingPlayers: holdingPlayers()")],
  ["holding cancels gain", js.includes("penaltyText || advanceDrive") && js.includes("success: !penaltyText")],
  ["pocket penalty logging", js.includes("contactPenalty") && js.includes("足場の悪い投球")],
  ["slow playback state", js.includes("speedScale") && js.includes("setSpeedScale") && js.includes("dt * state.speedScale")],
  ["pause controls", js.includes("setPaused") && js.includes("state.paused") && js.includes('event.key === "p"')],
  ["event banners", js.includes("showBanner") && js.includes("HIT AS THROWN") && js.includes("INCOMPLETE") && js.includes("TACKLE")],
  ["snapshot playback observability", js.includes("banner: state.banner") && js.includes("paused: state.paused")],
  ["replay frame recording", js.includes("recordReplayFrame") && js.includes("drawReplayFrame") && js.includes("replayFrames")],
  ["replay controls", js.includes("startReplay") && js.includes('event.key === "l"') && js.includes("replaying: state.replaying")],
  ["replay frame stepping", js.includes("showReplayFrame") && js.includes("updateReplayControls") && js.includes("replayIndex: state.replayIndex")],
  ["replay event markers", js.includes("replayMarkers") && js.includes("renderReplayMarkers") && js.includes("marker.frame")],
  ["replay marker snapshot", js.includes("replayMarkers: state.replayMarkers.map")],
  ["replay scrubber styling", css.includes("#replayScrubber") && css.includes("#frameBackButton")],
  ["replay marker styling", css.includes(".marker-strip") && css.includes('button[data-kind="bad"]')],
  ["responsive CSS", css.includes("@media")],
  ["debug snapshot", js.includes("window.__playbookLab")],
];

let failed = 0;
for (const [name, ok] of checks) {
  console.log(`${ok ? "ok" : "ng"} ${name}`);
  if (!ok) failed += 1;
}

if (failed > 0) process.exit(1);
