/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "websocket-message.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(stackchan_websocket_v1_WebSocketMessage, stackchan_websocket_v1_WebSocketMessage, 4)


PB_BIND(stackchan_websocket_v1_AudioPcmStart, stackchan_websocket_v1_AudioPcmStart, AUTO)


PB_BIND(stackchan_websocket_v1_AudioPcmEnd, stackchan_websocket_v1_AudioPcmEnd, AUTO)


PB_BIND(stackchan_websocket_v1_AudioWavStart, stackchan_websocket_v1_AudioWavStart, AUTO)


PB_BIND(stackchan_websocket_v1_AudioWavEnd, stackchan_websocket_v1_AudioWavEnd, AUTO)


PB_BIND(stackchan_websocket_v1_AudioChunk, stackchan_websocket_v1_AudioChunk, 4)


PB_BIND(stackchan_websocket_v1_StateCommand, stackchan_websocket_v1_StateCommand, AUTO)


PB_BIND(stackchan_websocket_v1_WakeWordEvent, stackchan_websocket_v1_WakeWordEvent, AUTO)


PB_BIND(stackchan_websocket_v1_StateEvent, stackchan_websocket_v1_StateEvent, AUTO)


PB_BIND(stackchan_websocket_v1_SpeakDoneEvent, stackchan_websocket_v1_SpeakDoneEvent, AUTO)


PB_BIND(stackchan_websocket_v1_ServoCommandSequence, stackchan_websocket_v1_ServoCommandSequence, 2)


PB_BIND(stackchan_websocket_v1_ServoCommand, stackchan_websocket_v1_ServoCommand, AUTO)


PB_BIND(stackchan_websocket_v1_ServoDoneEvent, stackchan_websocket_v1_ServoDoneEvent, AUTO)


PB_BIND(stackchan_websocket_v1_FirmwareMetadata, stackchan_websocket_v1_FirmwareMetadata, AUTO)


PB_BIND(stackchan_websocket_v1_ServerMetadata, stackchan_websocket_v1_ServerMetadata, AUTO)
