[platformio]
default_envs = m5stack-cores3-m5unified
; default_envs = m5stack-atoms3r-m5unified
; default_envs = m5stack-atom-echos3r-m5unified

extra_configs = platformio-m5stack.ini

src_dir = firmware/src
include_dir = firmware/include
lib_dir = firmware/lib

[env]
monitor_speed = 115200
monitor_filters = esp32_exception_decoder, time
upload_speed = 1500000

build_flags =
    -DSTACKCHAN_FIRMWARE_VERSION=\"0.1.0\"
lib_deps =
    adafruit/Adafruit NeoPixel@^1.15.2
    Links2004/WebSockets@^2.7.2
    ESP32Async/AsyncTCP@^3.4.10
    madhephaestus/ESP32Servo@^3.1.3
    nanopb/Nanopb@^0.4.91
    https://github.com/74th/ESP-SR-For-M5Unified.git@1.0.0
    https://github.com/mongonta0716/SCServo.git

lib_ldf_mode = deep

# For ESP-SR
extra_scripts = misc/ESP_SR/flash_srmodels.py

; upload_port = COM16
; monitor_port = ${env.upload_port}

[build-target]
; extends = release
extends = debug

[release]
build_type = release
build_flags =
    ${env.build_flags}
    -DCORE_DEBUG_LEVEL=3

[debug]
build_type = debug
build_flags =
    ${env.build_flags}
    -DCORE_DEBUG_LEVEL=4 -DDEBUG

[env:m5stack-cores3-m5unified]
extends = m5stack-cores3, m5unified, build-target
build_flags =
    ${m5stack-cores3.build_flags}
    ${m5unified.build_flags}
    ${build-target.build_flags}
lib_deps =
    ${m5stack-cores3.lib_deps}
    ${m5unified.lib_deps}
board_build.partitions = misc/ESP_SR/partitions_esp_sr_16.csv

[env:m5stack-official-stackchan]
extends = m5stack-cores3, m5unified, build-target
build_flags =
    ${m5stack-cores3.build_flags}
    ${m5unified.build_flags}
    ${build-target.build_flags}
    -DUSE_STACKCHAN_BSP=1
lib_deps =
    ${m5stack-cores3.lib_deps}
    ${m5unified.lib_deps}
    https://github.com/m5stack/StackChan-BSP.git
lib_ignore =
     SCServo
board_build.partitions = misc/ESP_SR/partitions_esp_sr_16.csv

[env:m5stack-atoms3r-m5unified]
extends = m5stack-atoms3r, m5unified, build-target
build_flags =
    ${m5stack-atoms3r.build_flags}
    ${m5unified.build_flags}
    ${build-target.build_flags}
lib_deps =
    ${m5stack-atoms3r.lib_deps}
    ${m5unified.lib_deps}
board_build.partitions = misc/ESP_SR/partitions_esp_sr_8.csv

[env:m5stack-atom-echos3r-m5unified]
extends = m5stack-atom-echos3r, m5unified, build-target
build_flags =
    ${m5stack-atom-echos3r.build_flags}
    ${m5unified.build_flags}
    ${build-target.build_flags}
lib_deps =
    ${m5stack-atom-echos3r.lib_deps}
    ${m5unified.lib_deps}
board_build.partitions = misc/ESP_SR/partitions_esp_sr_8.csv
