; Generated by tools/build_audio.py; fixed-bank callback for this Super FX ROM.
.setcpu "65816"
.smart
.export LoadAudioData: far
.export Tad_Loader_Bin := audio_data
.export Tad_Loader_SIZE = 116
.export Tad_AudioDriver_Bin := audio_data + 116
.export Tad_AudioDriver_SIZE = 3221
.import TAD_IO_VERSION
.assert TAD_IO_VERSION = 20, lderror, "TAD IO version mismatch"
.segment "BOOT"
.a8
.i16
LoadAudioData:
  cmp #0
  beq common
  cmp #1
  beq song
  clc
  rtl
common:
  lda #.bankbyte(audio_data + 3345)
  ldx #.loword(audio_data + 3345)
  ldy #6209
  sec
  rtl
song:
  lda #.bankbyte(audio_data + 9554)
  ldx #.loword(audio_data + 9554)
  ldy #8692
  sec
  rtl
.segment "AUDIO0"
audio_data: .incbin "data.bin"
.assert .bankbyte(audio_data) = .bankbyte(audio_data + 18246 - 1), lderror, "Audio data crosses bank"
