[env:m5stickc]
platform = https://github.com/pioarduino/platform-espressif32.git#55.03.36
board = m5stick-c
board_build.variant = m5stack_stickc
framework = arduino
monitor_speed = 115200
upload_speed = 115200
lib_deps =
  m5stack/M5Unified@0.2.22
